### ISSUE TITLE
StringFormat does not apply in MultiSelectionComboBox selection

### ISSUE THREAD

**Issue by ExLuzZziVo** [timunie/TimsWpfControls#12]
Hi,

There is an issue with MultiSelectionComboBox: if I want to apply ItemStringFormat, it is only gets applied on items in dropdown, but not on items in combobox's total text field. Please, take a look at example screenshot

![1](https://user-images.githubusercontent.com/46676089/103396688-a18b0000-4b45-11eb-9020-20dd42bb515e.png)

Steps to reproduce:

1. Create ViewModel
```csharp
public class ViewModel: INotifyPropertyChanged
{

        private ObservableCollection<DateTime> _dateTimes = new ObservableCollection<DateTime>() {DateTime.Now, new DateTime(2019, 4, 23)};
        public ObservableCollection<DateTime> DateTimes
        {
            get => _dateTimes;
            set
            {
                _dateTimes = value;
                OnPropertyChanged(nameof(DateTimes));
            }
        }
        
        [field: NonSerialized] public event PropertyChangedEventHandler PropertyChanged;

        private void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
}
```
2. Add MultiSelectionComboBox control to XAML and bind it to ViewModel
```csharp
<timsWpfControls:MultiSelectionComboBox SelectionMode="Multiple" ItemsSource="{Binding DateTimes}" ItemStringFormat="{}{0:D}"/>
```
3. Select all items and see the result

**Comment by timunie** [comment]
Hi @ExLuzZziVo 

Thank you for posting this 🙏 . I am transferring this control to MahApps (see https://github.com/MahApps/MahApps.Metro/pull/4006 ) and will address this issue there. 

I think for now you should be able to overcome this by using a custom `SelectedItemTemplate` 

Here is the original: https://github.com/timunie/TimsWpfControls/blob/0ff6be058363e20930c343462ee56b3ff9144743/TimsWpfControls/TimsWpfControls/Themes/MultiSelectionComboBox.xaml#L16-L54

 Happy coding and a happy new year 
Tim

**Comment by ExLuzZziVo** [comment]
I have found a solution. In GetSelectedItemsText method of MultiSelectionComboBox.cs I have used this code and it works:
```csharp
            IEnumerable<object> values;

            if (ReadLocalValue(DisplayMemberPathProperty) != DependencyProperty.UnsetValue && !string.IsNullOrEmpty(DisplayMemberPath))
            {
                values = ((IEnumerable<object>)SelectedItems)?.Select(o => BindingHelper.Eval(o, DisplayMemberPath ?? string.Empty));
            }
            else
            {
                values = (IEnumerable<object>)SelectedItems;
            }

            if (values != null && ReadLocalValue(ItemStringFormatProperty) != DependencyProperty.UnsetValue &&
                !string.IsNullOrEmpty(ItemStringFormat))
            {
                values = values.Select(o => string.Format(ItemStringFormat, o));
            }
```

**Comment by timunie** [comment]
@ExLuzZziVo thank you for providing your solution. I think I found an even better way, but it will not be implemented here. It will be available in MahApps soon (no due date right now). 

Happy new year and happy coding 
Tim

**Comment by ExLuzZziVo** [comment]
@timunie Thank you. I will close the issue
