### ISSUE TITLE
MultiSelectionComboBox - How to get SelectedItems

### ISSUE THREAD

**Issue by GWawrzeniecki** [timunie/TimsWpfControls#14]
Hello
This is rather a question not an issue.
I use your MultiSelectionComboBox since it isn't avaible yet in Mahapps.
Like this:

`   <controls:MultiSelectionComboBox x:Name="multiSelectComboBox" MinWidth="150" 
                                      
                                      VerticalAlignment="Center"
                                      Margin="5"
                                      IsEditable="False"
                                      IsReadOnly="False"
                                      mah:TextBoxHelper.ClearTextButton="True"
                                      mah:TextBoxHelper.Watermark="Proszę wybrać walidację"
                                      ItemTemplate="{DynamicResource Tims.DataTemplates.MultiSelectionComboBox.CheckBox2}"
                                      SelectedItemsTemplate="{DynamicResource Tims.DataTemplates.MultiSelectionComboBox.Removeable2}"
                                      SelectionMode="Multiple"
                                      Separator=", "
                                      ItemsSource="{Binding CheckModels}">`

I have changed the `Tims.DataTemplates.MultiSelectionComboBox.CheckBox`
Only here
` Content="{Binding Content}"`

And I have changed the `Tims.DataTemplates.MultiSelectionComboBox.Removeable`
Only here
` Content="{Binding Content}"`

My model from ItemSource looks like this:

` public class CheckModel : BusinessBase
    {
      

        private string _content;
        private bool _isChecked;
        private Func<Progress<ProgressReportModel>, Task> _checkTask;
        private Progress<ProgressReportModel> _progressReportModel;

        public Progress<ProgressReportModel> ProgressReportModel
        {
            get { return _progressReportModel; }
            set { SetProperty(ref _progressReportModel, value); }
        }
        public string Content
        {
            get { return _content; }
            set { SetProperty(ref _content, value); }
        }

        public override bool HasErrors => false;

        public bool IsChecked
        {
            get { return _isChecked; }
            set { 
                SetProperty(ref _isChecked, value); 
             
            }
        }

      
        public Func<Progress<ProgressReportModel>, Task> CheckTask
        {
            get { return _checkTask; }
            set { SetProperty(ref _checkTask, value); }
        }
    }`

And my question is how can I bind IsChecked property from ComboBox to IsChecked property in my ViewModel.
Since one binding has to be like this:
` IsChecked="{Binding RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=ListBoxItem}, Path=IsSelected, Mode=TwoWay}"`

**Comment by timunie** [comment]
Hi @GWawrzeniecki 

Seems like this is a bug comming from WPF itself. I tried several ways on my own but didn't find a solution so far 😢 
- use `DataTemplate` ► Same issue you have 
- use `ItemContainerStyle` ► works in 70 % of the cases, but not always. Does not work if the `Popup` was not shown first. Nothing to do here
- searching the web gave me: https://stackoverflow.com/questions/12466967/listbox-isselected-databinding-in-datatemplate

My conclusion is that we need to manually add / remove this in `MultiSelectionComboBox.SelectedItems` until I found a solution. 

Note: I am transferring this control to MahApps. Maybe someone there will have a solution. 

Happy coding
Tim

**Comment by GWawrzeniecki** [comment]
Hi @timunie 
At first, Thank you very much for your time!
I manged to resolve it with following code!


            '<controls:MultiSelectionComboBox.Resources>
                <Style TargetType="ListBoxItem">
                    <Setter Property="IsSelected"
                    Value="{Binding IsChecked, Mode=TwoWay}" />
                </Style>
            </controls:MultiSelectionComboBox.Resources>'

**Comment by timunie** [comment]
@GWawrzeniecki Be aware that this does not work in every case! Try to select an item in your model on start up- You may notice that it does not work.

**Comment by GWawrzeniecki** [comment]
Oh indeed. But in my use case I don't select items from code.

**Comment by timunie** [comment]
That is what I would like to do, so in my case I need to handle it differently. At least I have to state this in the docs for the new implementation on MahApps.

**Comment by GWawrzeniecki** [comment]
Here you are a few another solutions [https://stackoverflow.com/questions/9880589/bind-to-selecteditems-from-datagrid-or-listbox-in-mvvm](url) 
Maybe one of them will suit your needs

**Comment by timunie** [comment]
closing this as not planned now that we have the control in MahApps.
